#!/bin/sh
set -eu
ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
"$ROOT/tools/build.sh"
sh -n "$ROOT/dist/oum-test.sh"
sh -n "$ROOT/tools/build-installer.sh"
"$ROOT/tools/build-installer.sh"
"$ROOT/dist/oum-install.sh" --check
ruby -c "$ROOT/helpers/source_converter.rb"
ruby -c "$ROOT/luci-app-oum/root/usr/libexec/oum-policy-yaml.rb"
ruby -c "$ROOT/luci-app-oum/root/usr/libexec/oum-backup-codec.rb"
ruby -c "$ROOT/tests/test_backup_codec.rb"
sh -n "$ROOT/tools/install-luci-dev.sh"
sh -n "$ROOT/tools/oum-install-header.sh"
sh -n "$ROOT/tools/stage-engine-assets.sh"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-firstboot"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-source-job"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-reset-first-run"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-mihomo-api"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-openclash-nodes"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-passwall-nodes"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-passwall-policy"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-passwall-source-job"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-device-policy"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-subscription-info"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-backup"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-reset-vpn"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-system-job"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-engine-manager"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-podkop-config"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-awg-manager"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-dns-manager"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-mesh-manager"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-mesh-runtime"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-project-manager"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-zapret-strategy"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-zapret-quic"
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-zapret-manager"
OUM_ZAPRET_CATALOG="$ROOT/luci-app-oum/root/usr/share/oum/zapret-youtube-strategies" "$ROOT/luci-app-oum/root/usr/libexec/oum-zapret-strategy" validate
sh -n "$ROOT/luci-app-oum/root/usr/libexec/oum-login-default"
sh -n "$ROOT/tests/test_subscription_info.sh"
sh -n "$ROOT/tests/test_login_default.sh"
sh -n "$ROOT/tests/test_contracts.sh"
sh -n "$ROOT/tests/test_device_alias.sh"
sh -n "$ROOT/tests/test_device_pause.sh"
sh -n "$ROOT/luci-app-oum/root/etc/uci-defaults/90_oum_firstboot"
sh -n "$ROOT/luci-app-oum/root/etc/uci-defaults/91_oum_login_default"
python3 -m json.tool "$ROOT/luci-app-oum/root/usr/share/luci/menu.d/luci-app-oum.json" >/dev/null
grep -Fq "action_logout" "$ROOT/luci-app-oum/root/usr/share/ucode/luci/controller/oum.uc"
python3 -m json.tool "$ROOT/luci-app-oum/root/usr/share/rpcd/acl.d/luci-app-oum.json" >/dev/null
if command -v node >/dev/null 2>&1; then
	node --check "$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/first-run-v2.js"
	node --check "$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/dashboard-v11.js"
	node --check "$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/settings-v4.js"
fi
printf 'syntax tests: OK\n'
