#!/bin/sh

set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
SETTINGS="$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/settings-v43.js"
RPC="$ROOT/luci-app-oum/root/usr/share/rpcd/ucode/oum"
JOB="$ROOT/luci-app-oum/root/usr/libexec/oum-system-job"
ACL="$ROOT/luci-app-oum/root/usr/share/rpcd/acl.d/luci-app-oum.json"

grep -Fq "engineActionLabel = engineMissing ? 'Установить движок' : 'Заменить движок'" "$SETTINGS"
grep -Fq "dnsSelect('dns-current'" "$SETTINGS"
grep -Fq "callSetEngineDnsPreferences(engines.current, activeServer, activeBootstrap)" "$SETTINGS"
! grep -Fq "dnsSelect('dns-openclash'" "$SETTINGS"
grep -Fq 'showEngineJob' "$SETTINGS"
grep -Fq 'engineStageInfo' "$SETTINGS"
grep -Fq 'oum-engine-step-list' "$SETTINGS"
grep -Fq "label: 'Подготовка компонентов OUM'" "$SETTINGS"
grep -Fq "label: 'Проверка прямого интернета'" "$SETTINGS"
grep -Fq "label: 'Удаление прежних VPN-движков'" "$SETTINGS"
grep -Fq "label: 'Обновление каталога OpenWrt'" "$SETTINGS"
grep -Fq "label: 'Загрузка и проверка нового движка'" "$SETTINGS"
grep -Fq "label: 'Чистая установка нового движка'" "$SETTINGS"
grep -Fq "reconnecting: 96" "$SETTINGS"
grep -Fq 'oum-engine-progress-bar' "$SETTINGS"
! grep -Fq 'oum-engine-progress-ring' "$SETTINGS"
grep -Fq "window.sessionStorage.setItem('oum-engine-switch-title', title)" "$SETTINGS"
grep -Fq 'Перезагрузить сейчас' "$SETTINGS"
grep -Fq 'Позже' "$SETTINGS"
grep -Fq 'rebootRouter:' "$RPC"
grep -Fq 'reboot_required:' "$RPC"
grep -Fq 'reboot-required' "$JOB"
grep -Fq 'rebootRouter' "$ACL"
grep -Fq 'requested_engine="$(json_value .engine)"' "$JOB"
grep -Fq 'oum.main.dns_$engine=$server' "$JOB"
! grep -Fq 'oum.main.dns_openclash=$openclash' "$JOB"
grep -Fq "method: 'updateVpnEngine'" "$SETTINGS"
grep -Fq "id: 'update-engine'" "$SETTINGS"
grep -Fq "engines.current === 'openclash' || engines.current === 'podkop'" "$SETTINGS"
grep -Fq 'updateVpnEngine:' "$RPC"
grep -Fq 'engine_update)' "$JOB"
grep -Fq 'updateVpnEngine' "$ACL"
grep -Fq 'update) update_engine' "$ROOT/luci-app-oum/root/usr/libexec/oum-engine-manager"
grep -Fq 'download_engine "$TARGET"' "$ROOT/luci-app-oum/root/usr/libexec/oum-engine-manager"
grep -Fq 'проверяем SHA-256' "$ROOT/luci-app-oum/root/usr/libexec/oum-engine-manager"

printf 'engine UX tests: OK\n'
