#!/bin/sh

set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
BACKUP="$ROOT/luci-app-oum/root/usr/libexec/oum-backup"
RESET="$ROOT/luci-app-oum/root/usr/libexec/oum-reset-vpn"
ENGINE="$ROOT/luci-app-oum/root/usr/libexec/oum-engine-manager"
RPC="$ROOT/luci-app-oum/root/usr/share/rpcd/ucode/oum"
PODKOP="$ROOT/luci-app-oum/root/usr/libexec/oum-podkop-config"
AWG="$ROOT/luci-app-oum/root/usr/libexec/oum-awg-manager"
DNS="$ROOT/luci-app-oum/root/usr/libexec/oum-dns-manager"
MESH="$ROOT/luci-app-oum/root/usr/libexec/oum-mesh-manager"
MESH_RUNTIME="$ROOT/luci-app-oum/root/usr/libexec/oum-mesh-runtime"
USB_MANAGER="$ROOT/luci-app-oum/root/usr/libexec/oum-usb-manager"
PROJECT="$ROOT/luci-app-oum/root/usr/libexec/oum-project-manager"
OPENCLASH_NODES="$ROOT/luci-app-oum/root/usr/libexec/oum-openclash-nodes"
ZAPRET_STRATEGY="$ROOT/luci-app-oum/root/usr/libexec/oum-zapret-strategy"
ZAPRET_QUIC="$ROOT/luci-app-oum/root/usr/libexec/oum-zapret-quic"
ZAPRET_MANAGER="$ROOT/luci-app-oum/root/usr/libexec/oum-zapret-manager"
PASSWALL_SOURCE="$ROOT/luci-app-oum/root/usr/libexec/oum-passwall-source-job"
PASSWALL_BYPASS="$ROOT/luci-app-oum/root/usr/libexec/oum-passwall-bypass-russia"
DASHBOARD="$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/dashboard-v57.js"
SETTINGS="$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/settings-v43.js"
FIRST_RUN="$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/first-run-v2.js"
PARENTAL="$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/parental-v3.js"
HELP="$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/help-v3.js"
OUM_CSS="$ROOT/luci-app-oum/htdocs/luci-static/resources/oum/oum.css"

for view in "$DASHBOARD" "$SETTINGS" "$FIRST_RUN" "$PARENTAL" "$HELP"; do
	grep -Fq "L.resource('oum/oum.css')" "$view"
	! grep -Fq "E('style'" "$view"
done
grep -Fq -- '--oum-canvas: #eef0ea' "$OUM_CSS"
grep -Fq -- '--oum-console: #172c28' "$OUM_CSS"
grep -Fq -- '--oum-action: #2868d7' "$OUM_CSS"
grep -Fq 'outline: 3px solid var(--oum-action-ring)' "$OUM_CSS"
grep -Fq '.oum-vpn-switchboard' "$OUM_CSS"
! grep -Eq '#ccd3dc|#d8dde5|#2673ec' "$OUM_CSS" "$DASHBOARD" "$SETTINGS" "$FIRST_RUN" "$PARENTAL" "$HELP"

grep -Fq 'OUM_BACKUP_VERSION=2' "$BACKUP"
grep -Fq 'ENGINE=%s' "$BACKUP"
grep -Fq 'passwall)' "$BACKUP"
grep -Fq 'podkop)' "$BACKUP"
grep -Fq '/etc/config/zapret' "$BACKUP"
grep -Fq 'passwall-before-vpn-reset' "$RESET"
grep -Fq 'podkop-before-vpn-reset' "$RESET"
grep -Fq 'PACKAGE_CACHE=/etc/oum/packages' "$ENGINE"
grep -Fq 'stage_asset passwall' "$ENGINE"
grep -Fq '/etc/uci-defaults/luci-passwall' "$ENGINE"
grep -Fq 'PassWall configuration was not created.' "$ENGINE"
grep -Fq '/usr/libexec/oum-passwall-bypass-russia "$node"' "$PASSWALL_SOURCE"
grep -Fq 'geosite:category-ru' "$PASSWALL_BYPASS"
grep -Fq 'geosite:tld-ru' "$PASSWALL_BYPASS"
grep -Fq 'geosite:cn' "$PASSWALL_BYPASS"
grep -Fq 'geoip:cn' "$PASSWALL_BYPASS"
grep -Fq 'geosite:category-games-!cn' "$PASSWALL_BYPASS"
grep -Fq 'geosite:discord' "$PASSWALL_BYPASS"
grep -Fq 'oum_discord=_default' "$PASSWALL_BYPASS"
grep -Fq 'protocol=bittorrent' "$PASSWALL_BYPASS"
grep -Fq 'geosite:apple-update' "$PASSWALL_BYPASS"
grep -Fq 'geosite:google-play' "$PASSWALL_BYPASS"
grep -Fq "remote_dns='1.1.1.1:53'" "$PASSWALL_BYPASS"
grep -Fq 'passwall-before-source' "$PASSWALL_SOURCE"
grep -Fq 'subscribe.lua' "$PASSWALL_SOURCE"
grep -Fq "fail unsupported_type 'AWG" "$PASSWALL_SOURCE"
grep -Fq "OUM_RUNTIME='curl ruby ruby-yaml unzip'" "$ENGINE"
grep -Fq "OUM_CORE_RUNTIME='luci-base rpcd rpcd-mod-ucode uhttpd uhttpd-mod-ubus ubus ubusd libubus20251202 procd netifd firewall4 dnsmasq'" "$ENGINE"
! grep -Fq 'control_plane_checkpoint' "$ENGINE"
! grep -Fq "ruby -ryaml -e" "$ENGINE"
grep -Fq 'ensure_oum_runtime || die' "$ENGINE"
grep -Fq 'download_podkop' "$ENGINE"
grep -Fq 'download_access()' "$ENGINE"
grep -Fq 'stop_engine "$CURRENT"' "$ENGINE"
grep -Fq 'restart_previous_engine' "$ENGINE"
grep -Fq 'Без VPN нет доступа к GitHub или репозиторию OpenWrt.' "$ENGINE"
grep -Fq 'remove_all_engines || die' "$ENGINE"
grep -Fq 'Выполняем чистую установку нового движка' "$ENGINE"
! grep -Fq 'save_engine' "$ENGINE"
! grep -Fq 'rollback()' "$ENGINE"
! grep -Fq 'simulate_engine' "$ENGINE"
remove_line="$(grep -nF 'remove_all_engines || die' "$ENGINE" | cut -d: -f1)"
download_line="$(grep -nF 'download_engine "$TARGET" || die' "$ENGINE" | tail -n 1 | cut -d: -f1)"
[ "$remove_line" -lt "$download_line" ]
grep -Fq 'apk add --no-scripts --allow-untrusted' "$ENGINE"
grep -Fq '/etc/uci-defaults/zapret-uci-def-cfg.sh' "$ENGINE"
grep -Fq 'Zapret UCI configuration was not created.' "$ENGINE"
grep -Fq 'PodkopTable' "$ENGINE"
grep -Fq 'nft delete table inet zapret' "$ENGINE"
grep -Fq "pgrep -f '^/opt/zapret/nfq/nfqws '" "$ENGINE"
grep -Fq 'OUM_SKIP_ZAPRET' "$ENGINE"
! grep -Fq 'OUM_ENABLE_ZAPRET_ON_SWITCH' "$ENGINE"
grep -Fq 'uci -q set zapret.config.run_on_boot=0' "$ENGINE"
grep -Fq 'apk del $packages' "$ENGINE"
! grep -Fq -- '--no-prune' "$ENGINE"
grep -Fq 'world_constrained()' "$ENGINE"
grep -Fq 'download_engine "$TARGET" || die' "$ENGINE"
grep -Fq '/usr/libexec/oum-awg-manager install' "$ROOT/tools/oum-install-header.sh"
! grep -Fq 'OUM_INSTALL_AWG' "$ROOT/tools/oum-install-header.sh"
! grep -Fq 'OUM_SKIP_AWG' "$ROOT/tools/oum-install-header.sh"
! grep -Fq 'AmneziaWG заблокирован для AX6S с ядром 6.12.85' "$AWG"
! grep -Fq 'AmneziaWG несовместим' "$AWG"
grep -Fq "engine in [ 'openclash', 'passwall', 'podkop' ]" "$RPC"
grep -Fq "engineChoice('openclash'" "$SETTINGS"
grep -Fq 'Настройки старого движка не переносятся.' "$SETTINGS"
grep -Fq 'configurePodkop' "$RPC"
grep -Fq 'importPodkopAwg' "$RPC"
grep -Fq 'importPodkopReality' "$RPC"
grep -Fq 'setPodkopYoutubeMode' "$RPC"
grep -Fq '/usr/libexec/oum-passwall-source-job' "$RPC"
grep -Fq 'podkopRoutingStatus' "$RPC"
grep -Fq 'applyPodkopRouting' "$RPC"
grep -Fq 'podkopDiagnostics' "$RPC"
grep -Fq 'podkopInstalled()' "$RPC"
grep -Fq 'not silently replace WS_USER' "$PODKOP"
! grep -Fq "sed -i 's/^WS_USER=" "$PODKOP"
grep -Fq 'must not escalate the daemon to root' "$ZAPRET_STRATEGY"
! grep -Fq "sed -i 's/^WS_USER=" "$ZAPRET_STRATEGY"
grep -Fq 'ensure_podkop_defaults' "$PODKOP"
grep -Fq 'podkop_managed_youtube_proxy' "$PODKOP"
grep -Fq 'start_zapret_verified' "$PODKOP"
! grep -Fq 'delete podkop.settings.routing_excluded_ips' "$PODKOP"
! grep -Fq "set podkop.settings.disable_quic='0'" "$PODKOP"
grep -Fq 'route_allowed_ips=0' "$AWG"
grep -Fq 'Slava-Shchipunov/awg-openwrt/$UPSTREAM_COMMIT/amneziawg-install.sh' "$AWG"
grep -Fq 'UPSTREAM_COMMIT=9742aa540b72c4059dabe8e91366162a98499219' "$AWG"
grep -Fq 'UPSTREAM_INSTALLER_SHA256=8f556021e874053836e73c0be8cbf006706f22890da78bc9be9ff0cb93b7229c' "$AWG"
grep -Fq 'sh "$WORK/amneziawg-install.sh" -e -n' "$AWG"
! grep -Fq 'refs/heads/master/amneziawg-install.sh' "$AWG"
grep -Fq 'DNS policy is intentionally independent' "$AWG"
grep -Fq 'interface:s3)' "$AWG"
grep -Fq 'interface:i5)' "$AWG"
grep -Fq 'remove_managed' "$AWG"
grep -Fq 'disable_managed' "$AWG"
grep -Fq 'enable_managed' "$AWG"
grep -Fq 'runtime_ready' "$AWG"
grep -Fq 'network.$INTERFACE.auto=0' "$AWG"
grep -Fq 'oum_managed' "$AWG"
grep -Fq 'preflight_runtime' "$AWG"
grep -Fq 'reboot-required-awg' "$AWG"
"$AWG" validate "$ROOT/tests/fixtures/awg-v2.conf" >/dev/null
grep -Fq '/usr/libexec/oum-awg-manager disable' "$ENGINE"
! grep -Fq '/usr/libexec/oum-awg-manager remove' "$ENGINE"
! grep -Fq '/usr/libexec/oum-awg-manager install' "$ENGINE"
grep -Fq 'saved_podkop_awg()' "$ENGINE"
grep -Fq 'activate_saved_podkop_awg()' "$ENGINE"
grep -Fq '/usr/libexec/oum-awg-manager enable' "$ENGINE"
grep -Fq '/usr/libexec/oum-podkop-config configure oum_awg' "$ENGINE"
grep -Fq '/usr/libexec/oum-awg-manager install' "$ROOT/tools/oum-install-header.sh"
grep -Fq '/usr/libexec/oum-awg-manager ready' "$ROOT/luci-app-oum/root/usr/libexec/oum-system-job"
! grep -Fq "write_status success rebooting" "$ROOT/luci-app-oum/root/usr/libexec/oum-system-job"
grep -Fq 'nft -a list chain' "$OPENCLASH_NODES"
grep -Fq 'OUM-probe' "$OPENCLASH_NODES"
grep -Fq 'OPENCLASH_NODE_CACHE' "$RPC"
grep -Fq 'clearSystemJobStatus' "$RPC"
grep -Fq 'setEngineDnsPreferences' "$RPC"
grep -Fq 'bootstrap_openclash' "$RPC"
grep -Fq 'openclash: engines.openclash' "$RPC"
grep -Fq "id: 'openclash-panel'" "$DASHBOARD"
grep -Fq "width: '48', height: '48'" "$DASHBOARD"
grep -Fq '.oum-openclash-empty[hidden] { display: none !important; }' "$ROOT/luci-app-oum/htdocs/luci-static/resources/oum/oum.css"
grep -Fq "id: 'quick-node-list'" "$DASHBOARD"
grep -Fq "id: 'passwall-summary-badge'" "$DASHBOARD"
grep -Fq "id: 'passwall-active-node'" "$DASHBOARD"
grep -Fq "id: 'passwall-active-meta'" "$DASHBOARD"
grep -Fq 'nodePanelTitle.textContent = isPasswall ? `Ноды PassWall (${all.length})`' "$DASHBOARD"
grep -Fq 'const quick = preferredNodes(fresh).slice(0, 3)' "$DASHBOARD"
grep -Fq 'isPasswall ? `Показать все ${all.length}`' "$DASHBOARD"
grep -Fq '#node-panel:has(#passwall-panel:not([hidden]))' "$OUM_CSS"
grep -Fq '.oum-passwall-active' "$OUM_CSS"
grep -Fq "id: 'subscription-progress'" "$DASHBOARD"
grep -Fq "method: 'refreshSubscription'" "$DASHBOARD"
grep -Fq 'refreshSubscription:' "$RPC"
grep -Fq 'rm -f /tmp/oum-openclash-nodes.cache' "$ROOT/luci-app-oum/root/usr/libexec/oum-source-job"
grep -Fq 'preferredNodes(fresh).slice(0, 3)' "$DASHBOARD"
grep -Fq "countryKey(node.name) !== 'RU'" "$DASHBOARD"
grep -Fq "id: 'measure-nodes'" "$DASHBOARD"
grep -Fq '.oum-node-controls[data-engine="openclash"] .oum-current-node' "$ROOT/luci-app-oum/htdocs/luci-static/resources/oum/oum.css"
grep -Fq 'bootstrap_passwall' "$RPC"
grep -Fq 'bootstrap_podkop' "$RPC"
grep -Fq 'configure_openclash' "$DNS"
grep -Fq 'configure_passwall' "$DNS"
grep -Fq 'configure_podkop' "$DNS"
grep -Fq 'OUM_BOOTSTRAP_DNS' "$DNS"
grep -Fq 'bootstrap_dns_server=$BOOTSTRAP' "$DNS"
grep -Fq "wireless.oum_mesh.mode='mesh'" "$MESH"
grep -Fq "wireless.oum_mesh.mesh_fwding='1'" "$MESH"
grep -Fq 'applyMeshSettings' "$RPC"
grep -Fq 'installMeshRuntime' "$RPC"
grep -Fq 'usbStorageStatus' "$RPC"
grep -Fq "bus?.call('network.interface.wan', 'status')" "$RPC"
grep -Fq "cursor().get('fstab', 'oum_usb', 'target')" "$RPC"
grep -Fq 'prepareUsbStorage' "$RPC"
grep -Fq 'formatUsbStorage' "$RPC"
grep -Fq 'mountUsbStorage' "$RPC"
grep -Fq 'unmountUsbStorage' "$RPC"
grep -Fq 'setUsbSmb' "$RPC"
grep -Fq 'setUsbAria2' "$RPC"
grep -Fq 'setUsbDlna' "$RPC"
grep -Fq 'configureUsbSorter' "$RPC"
grep -Fq 'runUsbSorter' "$RPC"
grep -Fq "match(line, /^([a-z0-9_]+)=(.*)$/)" "$RPC"
grep -Fq 'case "$target" in */usb*/*)' "$USB_MANAGER"
grep -Fq "request.args.confirm != 'ERASE'" "$RPC"
grep -Fq '[ "${2:-}" = ERASE ]' "$USB_MANAGER"
grep -Fq "set fstab.\$FSTAB_SECTION.uuid='\$uuid'" "$USB_MANAGER"
grep -Fq 'mkfs.ext4 -F -T largefile -m 0 -E lazy_itable_init=1,lazy_journal_init=1' "$USB_MANAGER"
! grep -Fq 'block detect > /etc/config/fstab' "$USB_MANAGER"
! grep -Fq 'chmod -R 777' "$USB_MANAGER"
grep -Fq "set ksmbd.@globals[0].interface='lan'" "$USB_MANAGER"
grep -Fq "set ksmbd.\$SMB_SHARE_SECTION.guest_ok='yes'" "$USB_MANAGER"
grep -Fq "delete ksmbd.\$SMB_SHARE_SECTION.force_root" "$USB_MANAGER"
! grep -Fq "force_root='1'" "$USB_MANAGER"
grep -Fq 'apk info -e ksmbd-server' "$USB_MANAGER"
grep -Fq '/etc/oum/usb/ksmbd-before-oum' "$USB_MANAGER"
grep -Fq "set aria2.\$ARIA2_SECTION.rpc_auth_method='token'" "$USB_MANAGER"
grep -Fq "set aria2.\$ARIA2_SECTION.rpc_secret='\$secret'" "$USB_MANAGER"
grep -Fq "set aria2.\$ARIA2_SECTION.dir='\$download_dir'" "$USB_MANAGER"
! grep -Fq "aria2-RPC" "$USB_MANAGER"
grep -Fq "set minidlna.\$DLNA_SECTION.interface='br-lan'" "$USB_MANAGER"
grep -Fq 'chmod 0711 "$root"' "$USB_MANAGER"
grep -Fq "add_list minidlna.\$DLNA_SECTION.media_dir='V,\$media_root/Movies'" "$USB_MANAGER"
grep -Fq "add_list minidlna.\$DLNA_SECTION.media_dir='A,\$media_root/Music'" "$USB_MANAGER"
! grep -Fq "minidlna-DLNA" "$USB_MANAGER"
grep -Fq "SORTER_PACKAGES='python3-light python3-codecs python3-openssl python3-urllib'" "$USB_MANAGER"
grep -Fq 'grep -Eq '\''^[A-Fa-f0-9]{32}$'\'' "$SORTER_KEY"' "$USB_MANAGER"
grep -Fq 'find "$SOURCE_DIR" -type f -name '\''*.aria2'\''' "$ROOT/luci-app-oum/root/usr/libexec/oum-media-organizer-run"
! grep -Fq 'tmdb_api_key' "$ROOT/luci-app-oum/root/usr/libexec/oum-system-job"
grep -Fq 'writePrivate('\''/etc/oum/tmdb_api_key'\''' "$RPC"
grep -Fq 'smb_disable' "$USB_MANAGER"
grep -Fq 'SWAP_SIZE_MB=512' "$USB_MANAGER"
grep -Fq 'swap-enable) swap_enable' "$USB_MANAGER"
grep -Fq 'swap-disable) swap_disable' "$USB_MANAGER"
grep -Fq 'deactivate_swap "$target"' "$USB_MANAGER"
grep -Fq "set fstab.\$SWAP_SECTION.device='\$swap_file'" "$USB_MANAGER"
grep -Fq "id: 'toggle-usb-smb'" "$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/settings-v58.js"
grep -Fq "id: 'toggle-usb-aria2'" "$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/settings-v58.js"
grep -Fq "id: 'toggle-usb-dlna'" "$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/settings-v58.js"
grep -Fq "id: 'configure-usb-sorter'" "$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/settings-v58.js"
grep -Fq "id: 'toggle-usb-swap'" "$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/settings-v58.js"
grep -Fq 'setUsbSwap' "$ROOT/luci-app-oum/root/usr/share/rpcd/acl.d/luci-app-oum.json"
grep -Fq 'configureUsbSorter' "$ROOT/luci-app-oum/root/usr/share/rpcd/acl.d/luci-app-oum.json"
grep -Fq 'runUsbSorter' "$ROOT/luci-app-oum/root/usr/share/rpcd/acl.d/luci-app-oum.json"
grep -Fq "id: 'prepare-usb-storage'" "$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/settings-v58.js"
grep -Fq "id: 'format-usb-storage'" "$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/settings-v58.js"
grep -Fq "launcher('USB'" "$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/settings-v58.js"
grep -Fq "systemMeter('storage-usb'" "$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/dashboard-v57.js"
grep -Fq '`WAN · ${port.device}`' "$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/dashboard-v57.js"
grep -Fq 'oum-usb-manager' "$ROOT/tools/install-luci-dev.sh"
grep -Fq "...(!meshReady && capabilities.mesh_runtime_bundle ? [ E('div'" "$SETTINGS"
! grep -Fq ']) : null,' "$SETTINGS"
grep -Fq 'wpad-mesh-mbedtls-$VERSION.apk' "$MESH_RUNTIME"
grep -Fq "MESH_SHA256='d3d22ced0e67219e86bd9e00f6dd1f960d3095c2637c9d344b509a45c8cab18b'" "$MESH_RUNTIME"
grep -Fq 'restore_basic' "$MESH_RUNTIME"
grep -Fq 'oum-install.sh' "$PROJECT"
grep -Fq 'sh "$INSTALLER" --check' "$PROJECT"
grep -Fq 'rollbackProject' "$RPC"
grep -Fq 'applyLanSettings' "$RPC"
grep -Fq "startSystemJob('lan'" "$RPC"
grep -Fq "network.lan.ipaddr='192.168.5.1'" "$ROOT/luci-app-oum/root/usr/libexec/oum-firstboot"
grep -Fq 'project_update' "$ROOT/luci-app-oum/root/usr/libexec/oum-system-job"
grep -Fq 'project_rollback' "$ROOT/luci-app-oum/root/usr/libexec/oum-system-job"
grep -Fq 'updateProject' "$SETTINGS"
grep -Fq 'rollbackProject' "$SETTINGS"
grep -Fq "OUM_BASE_PACKAGES='luci-base rpcd rpcd-mod-ucode" "$ROOT/tools/oum-install-header.sh"
grep -Fq 'iw iwinfo dnsmasq firewall4' "$ROOT/tools/oum-install-header.sh"
grep -Fq '+iw +iwinfo +dnsmasq +firewall4' "$ROOT/luci-app-oum/Makefile"
grep -Fq 'oum_install_base_packages' "$ROOT/tools/oum-install-header.sh"
grep -Fq 'podkop_awg' "$ROOT/luci-app-oum/root/usr/libexec/oum-system-job"
grep -Fq 'podkop_proxy' "$ROOT/luci-app-oum/root/usr/libexec/oum-system-job"
grep -Fq 'podkop_youtube' "$ROOT/luci-app-oum/root/usr/libexec/oum-system-job"
grep -Fq 'check_zapret_route' "$PODKOP"
grep -Fq '/usr/libexec/oum-zapret-strategy auto' "$PODKOP"
grep -Fq 'zapret_auto' "$ROOT/luci-app-oum/root/usr/libexec/oum-system-job"
grep -Fq 'startZapretStrategy' "$RPC"
grep -Fq 'zapretStrategyStatus' "$RPC"
grep -Fq 'CATALOG_REVISION=189abafd50aed17f8c7414695d0d47d129a6b0dd' "$ZAPRET_STRATEGY"
grep -Fq 'CATALOG_SHA256=6965340ed61797a7760bae74fd18d5c8a90a8a9f339f20c1cf9d57f5f6afdef2' "$ZAPRET_STRATEGY"
grep -Fq -- '--interface "$device"' "$ZAPRET_STRATEGY"
grep -Fq -- '--resolve "$host:443:$real_ip"' "$ZAPRET_STRATEGY"
grep -Fq 'Podkop DNS deliberately returns FakeIP addresses' "$ZAPRET_STRATEGY"
grep -Fq 'zapret_section()' "$ZAPRET_STRATEGY"
grep -Fq 'https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg' "$ZAPRET_STRATEGY"
! grep -Fq 'zapret.main.NFQWS_OPT' "$ZAPRET_STRATEGY"
grep -Fq 'restore_rollback' "$ZAPRET_STRATEGY"
grep -Fq 'acquire_lock' "$ZAPRET_STRATEGY"
grep -Fq 'setZapretQuic' "$RPC"
grep -Fq 'OUM Block QUIC UDP $port' "$ZAPRET_QUIC"
grep -Fq 'firewall-before-quic' "$ZAPRET_QUIC"
grep -Fq 'prepareZapretManager' "$RPC"
grep -Fq 'zapret_manager_install' "$ROOT/luci-app-oum/root/usr/libexec/oum-system-job"
grep -Fq 'REVISION=189abafd50aed17f8c7414695d0d47d129a6b0dd' "$ZAPRET_MANAGER"
grep -Fq 'SHA256=bf6a74b6f482690e6f5337217da17db4ebeb4ce16085a0315ba4fd1b5fce1693' "$ZAPRET_MANAGER"
grep -Fq 'Zapret Manager запускается только из интерактивной root SSH-сессии.' "$ZAPRET_MANAGER"
grep -Fq 'zapret-manager-before-session' "$ZAPRET_MANAGER"
grep -Fq 'zapret-manager-prepare' "$DASHBOARD"
grep -Fq 'check_dns_available' "$RPC"
grep -Fq 'Zapret / YouTube' "$RPC"
OUM_ZAPRET_CATALOG="$ROOT/luci-app-oum/root/usr/share/oum/zapret-youtube-strategies" "$ZAPRET_STRATEGY" validate
grep -Fq 'podkop_routing' "$ROOT/luci-app-oum/root/usr/libexec/oum-system-job"
grep -Fq 'data-podkop-tab' "$DASHBOARD"
grep -Fq 'podkop-diagnostic-grid' "$DASHBOARD"
grep -Fq 'RTT через AWG' "$RPC"
grep -Fq 'HTTP-проверка Reality' "$RPC"
grep -Fq 'podkop-awg-config' "$SETTINGS"
grep -Fq 'podkop-reality-config' "$SETTINGS"
grep -Fq 'Reality / Proxy' "$SETTINGS"
grep -Fq 'Стратегия Zapret' "$SETTINGS"
grep -Fq 'data-community-route' "$DASHBOARD"
grep -Fq 'Через VPN' "$DASHBOARD"
grep -Fq 'Напрямую + Zapret' "$DASHBOARD"
! grep -Fq 'ukraine_inside' "$DASHBOARD"
! grep -Fq "[ 'ukraine_inside', 'Украина' ]" "$RPC"
grep -Fq "callSetPodkopYoutubeMode('zapret', manual ? strategy : '')" "$SETTINGS"
grep -Fq 'Рабочим считается результат не хуже 3 из 4 проверок.' "$SETTINGS"
grep -Fq "/sbin/ip -4 neigh show" "$RPC"
grep -Fq 'routing_excluded_ips' "$ROOT/luci-app-oum/root/usr/libexec/oum-device-policy"
grep -Fq 'fully_routed_ips' "$ROOT/luci-app-oum/root/usr/libexec/oum-device-policy"
grep -Fq "'default', 'direct', 'gaming', 'vpn'" "$RPC"
grep -Fq 'Игры напрямую' "$DASHBOARD"
grep -Fq "GAME_ACL_REMARKS='OUM gaming direct'" "$ROOT/luci-app-oum/root/usr/libexec/oum-passwall-policy"
grep -Fq "GAME_TCP_PORTS='3074,3478-3480,5222-5223,27014-27050'" "$ROOT/luci-app-oum/root/usr/libexec/oum-passwall-policy"
grep -Fq "GAME_UDP_PORTS='88,500,3074,3478-3479,3544,3658,4379-4380,4500,27000-27200'" "$ROOT/luci-app-oum/root/usr/libexec/oum-passwall-policy"
grep -Fq 'unmanaged_tunnels' "$RPC"
grep -Fq "if (section.oum_managed == '1')" "$RPC"
grep -Fq 'дополнительное VPN-подключение, созданное не через OUM' "$SETTINGS"
grep -Fq "ubus list 'hostapd.*'" "$RPC"
grep -Fq "if (!client.seen)" "$RPC"
grep -Fq "length(args.admin_password) > 0 && length(args.admin_password) < 6" "$RPC"
grep -Fq "OUM_PAYLOAD_SHA256" "$ROOT/tools/oum-install-header.sh"
grep -Fq "OUM_PAYLOAD_SIZE" "$ROOT/tools/oum-install-header.sh"
grep -Fq 'tail -c "$OUM_PAYLOAD_SIZE"' "$ROOT/tools/oum-install-header.sh"
if grep -Fq 'oum_need base64' "$ROOT/tools/oum-install-header.sh"; then
	fail "standalone installer must not require base64 on OpenWrt"
fi
grep -Fq "oum_backup_current" "$ROOT/tools/oum-install-header.sh"
grep -Fq "oum_menu" "$ROOT/tools/oum-install-header.sh"
grep -Fq "1) Установить / обновить OUM" "$ROOT/tools/oum-install-header.sh"
grep -Fq "2) Первый запуск" "$ROOT/tools/oum-install-header.sh"
grep -Fq -- "--install) oum_install_package" "$ROOT/tools/oum-install-header.sh"
grep -Fq -- "--first-run) oum_first_run" "$ROOT/tools/oum-install-header.sh"
! grep -Fq 'wget -T 20 -t 3' "$ROOT/luci-app-oum/root/usr/libexec/oum-engine-manager"
grep -Fq 'wget --timeout=20' "$ROOT/luci-app-oum/root/usr/libexec/oum-engine-manager"
grep -Fq 'while [ "$attempt" -le 3 ]' "$ROOT/luci-app-oum/root/usr/libexec/oum-engine-manager"
grep -Fq 'openwrt-ultimate-manager/releases/download/passwall-26.5.11' "$ROOT/luci-app-oum/root/usr/libexec/oum-engine-manager"
! grep -Fq 'openwrt-ultimate-manager-assets' "$ROOT/luci-app-oum/root/usr/libexec/oum-engine-manager"
grep -Fq 'geosite.dat|c9a47d1a83134e3dcb57d5a3457408c3ed426ab0430718c85a44d3223aaad075' "$ROOT/luci-app-oum/root/usr/libexec/oum-engine-manager"
grep -Fq 'geoip.dat|8ebcb11333f7deed4bf2740f2ce3249aa8997ef03d437150c7ae373c011cd72a' "$ROOT/luci-app-oum/root/usr/libexec/oum-engine-manager"
grep -Fq '/etc/init.d/$CURRENT restart' "$ROOT/luci-app-oum/root/usr/libexec/oum-engine-manager"
grep -Fq "PASSWALL_SYSTEM='kmod-nft-tproxy kmod-nft-socket'" "$ROOT/luci-app-oum/root/usr/libexec/oum-engine-manager"
grep -Fq "directDns = 'Системный DNS'" "$RPC"
grep -Fq 'ipv6_filtered: ipv6Filtered' "$RPC"
grep -Fq "Фильтрация включена" "$DASHBOARD"

if grep -Rq 'test_speedtest_yaml' "$ROOT/.github"; then
	echo 'Removed speed-test test is still referenced' >&2
	exit 1
fi

printf 'OUM contract tests: OK\n'
