#!/bin/sh

set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
BACKUP="$ROOT/luci-app-oum/root/usr/libexec/oum-backup"
RESET="$ROOT/luci-app-oum/root/usr/libexec/oum-reset-vpn"
ENGINE="$ROOT/luci-app-oum/root/usr/libexec/oum-engine-manager"
RPC="$ROOT/luci-app-oum/root/usr/share/rpcd/ucode/oum"
PODKOP="$ROOT/luci-app-oum/root/usr/libexec/oum-podkop-config"
AWG="$ROOT/luci-app-oum/root/usr/libexec/oum-awg-manager"
ZAPRET_STRATEGY="$ROOT/luci-app-oum/root/usr/libexec/oum-zapret-strategy"
PASSWALL_SOURCE="$ROOT/luci-app-oum/root/usr/libexec/oum-passwall-source-job"
DASHBOARD="$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/dashboard-v11.js"

grep -Fq 'OUM_BACKUP_VERSION=2' "$BACKUP"
grep -Fq 'ENGINE=%s' "$BACKUP"
grep -Fq 'passwall)' "$BACKUP"
grep -Fq 'podkop)' "$BACKUP"
grep -Fq '/etc/config/zapret' "$BACKUP"
grep -Fq 'passwall-before-vpn-reset' "$RESET"
grep -Fq 'podkop-before-vpn-reset' "$RESET"
grep -Fq 'PACKAGE_CACHE=/etc/oum/packages' "$ENGINE"
grep -Fq 'stage_asset passwall' "$ENGINE"
grep -Fq '/etc/uci-defaults/luci-passwall' "$ENGINE"
grep -Fq 'PassWall configuration was not created.' "$ENGINE"
grep -Fq 'passwall-before-source' "$PASSWALL_SOURCE"
grep -Fq 'subscribe.lua' "$PASSWALL_SOURCE"
grep -Fq "fail unsupported_type 'AWG" "$PASSWALL_SOURCE"
grep -Fq "OUM_RUNTIME='curl ruby ruby-yaml unzip'" "$ENGINE"
grep -Fq 'ensure_oum_runtime || die' "$ENGINE"
grep -Fq 'download_podkop' "$ENGINE"
grep -Fq 'PodkopTable' "$ENGINE"
grep -Fq 'configurePodkop' "$RPC"
grep -Fq 'importPodkopAwg' "$RPC"
grep -Fq '/usr/libexec/oum-passwall-source-job' "$RPC"
grep -Fq 'podkopRoutingStatus' "$RPC"
grep -Fq 'applyPodkopRouting' "$RPC"
grep -Fq 'podkopDiagnostics' "$RPC"
grep -Fq 'podkopInstalled()' "$RPC"
grep -Fq 'WS_USER="root"' "$PODKOP"
grep -Fq 'route_allowed_ips=0' "$AWG"
grep -Fq 'mediatek_mt7622.apk' "$AWG"
grep -Fq 'DNS policy is intentionally independent' "$AWG"
grep -Fq 'interface:s3)' "$AWG"
grep -Fq 'interface:i5)' "$AWG"
"$AWG" validate "$ROOT/tests/fixtures/awg-v2.conf" >/dev/null
grep -Fq 'podkop_awg' "$ROOT/luci-app-oum/root/usr/libexec/oum-system-job"
grep -Fq 'zapret_auto' "$ROOT/luci-app-oum/root/usr/libexec/oum-system-job"
grep -Fq 'startZapretStrategy' "$RPC"
grep -Fq 'zapretStrategyStatus' "$RPC"
grep -Fq 'CATALOG_REVISION=189abafd50aed17f8c7414695d0d47d129a6b0dd' "$ZAPRET_STRATEGY"
grep -Fq 'CATALOG_SHA256=6965340ed61797a7760bae74fd18d5c8a90a8a9f339f20c1cf9d57f5f6afdef2' "$ZAPRET_STRATEGY"
grep -Fq -- '--interface "$device"' "$ZAPRET_STRATEGY"
grep -Fq 'zapret_section()' "$ZAPRET_STRATEGY"
grep -Fq 'https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg' "$ZAPRET_STRATEGY"
! grep -Fq 'zapret.main.NFQWS_OPT' "$ZAPRET_STRATEGY"
grep -Fq 'restore_rollback' "$ZAPRET_STRATEGY"
grep -Fq 'acquire_lock' "$ZAPRET_STRATEGY"
OUM_ZAPRET_CATALOG="$ROOT/luci-app-oum/root/usr/share/oum/zapret-youtube-strategies" "$ZAPRET_STRATEGY" validate
grep -Fq 'podkop_routing' "$ROOT/luci-app-oum/root/usr/libexec/oum-system-job"
grep -Fq 'data-podkop-tab' "$DASHBOARD"
grep -Fq 'podkop-diagnostic-grid' "$DASHBOARD"
grep -Fq 'podkop-awg-config' "$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/settings-v4.js"
grep -Fq 'Reality / Proxy' "$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/settings-v4.js"
grep -Fq 'Zapret для YouTube' "$ROOT/luci-app-oum/htdocs/luci-static/resources/view/oum/settings-v4.js"
grep -Fq 'unmanaged_tunnels' "$RPC"
grep -Fq "length(args.admin_password) < 6" "$RPC"

if grep -Rq 'test_speedtest_yaml' "$ROOT/.github"; then
	echo 'Removed speed-test test is still referenced' >&2
	exit 1
fi

printf 'OUM contract tests: OK\n'
